### ISSUE TITLE
Support for LIFX Bulbs

### ISSUE THREAD

**Issue by roxaskeyheart** [DarthAffe/RGB.NET#11]
Not sure if this is any help but if you were wanting to get LIFX (https://www.lifx.com) support in the future, maybe this would give you a bit of a head start?

https://github.com/dotMorten/LifxNet

https://github.com/roxaskeyheart/Chromatics/blob/master/Chromatics/DeviceInterfaces/LIFXInterface.cs

I've been working with this library for a bit now so feel free to ping me here or on your Discord if you'd like to chat about it, not entirely sure how your devices framework is setup yet, but I'd be keen to help implement it if you'd like.

**Comment by mk-mrshll** [comment]
@DarthAffe Have you started on this at all? I'd like to help out if I could. I was trying to figure out how the solution implements Philips Hue integration so that I could model LIFX after it, but I couldn't find anything in the code. How would you recommend I start out?

**Comment by DarthAffe** [comment]
Neither hue nor LIFX is currently implemented.
Since I haven't looked at how the SDKs are working I can't really give any advice on how to approach it.

**Comment by mk-mrshll** [comment]
> Neither hue nor LIFX is currently implemented.
> Since I haven't looked at how the SDKs are working I can't really give any advice on how to approach it.

Got it. Thanks! I'll take a crack at it when I can.
