### ISSUE TITLE
SteelSeries dispose fails if not initialized

### ISSUE THREAD

**Issue by SpoinkyNL** [DarthAffe/RGB.NET#113]
The code below calls `ResetLeds()` which in turn calls `StopGame()` but that fails because `PostJson()` has no `_baseUrl` to work with.

https://github.com/DarthAffe/RGB.NET/blob/0b761995823da592af27af74c8c35ddbf0b79505/RGB.NET.Devices.SteelSeries/API/SteelSeriesSDK.cs#L86

**Comment by DarthAffe** [comment]
This should be fixed in 1cfdeefde1f03300c4bd635099fa9929e55ce1e7
