### ISSUE TITLE
Corsair CUE does nothing?

### ISSUE THREAD

**Issue by mattmartinolc** [DarthAffe/RGB.NET#12]
Hi there. I have 6x HD120 corsair fans hooked to a commander pro and have them synchronizing with Aura. Everything seems ok except my corsair k55 keyboard (corsair cue) doesn't seem to do anything. Is this supported yet?

**Comment by DarthAffe** [comment]
The K55 isn't listed as a supported device in the CUE SDK documentation.
I expect it to be added with the next SDK-version, but I can't make any promises of what corsair will do, nor can I give you an estimation of when an update will be released.
