### ISSUE TITLE
More Logitech devices

### ISSUE THREAD

**Issue by Legion2** [DarthAffe/RGB.NET#126]
Name: Logitech G Pro Hero
Device Type: Mouse
VID: 046D
PID: C08C

Name: Logitech G512 SE Keyboard
Device Type: Keyboard
VID : 046D
PID : C342

Name: Logitech G502 Lightspeed
Device Type: Mouse
VID: 046D
PID: C539

**Comment by Legion2** [comment]
Name: Logitech G Pro Wireless 
Device Type: Mouse
VID : 046D
PID : C088

Name: Logitech G512SE Keyboard
Device Type: Keyboard
VID : 046D
PID : C332

C332 is already mapped to G502, is it possible the two devices have the same PID?
Also C539 is already used by G900 but was reported by a JackNet RGB Sync user to correspond to G502 Lightspeed.

Name: Logitech G502 Lightspeed
Device Type: Mouse
VID: 046D
PID: C539

**Comment by DarthAffe** [comment]
hmm maybe this is due to the device using the same wireless dongle or something like that. C332 is also documented here http://www.devicekb.com/usb-vendor/046D/device/C332.php to be the G502 and a vulnerability database has an entry for Logitech G900 dongle C-U0008 (USB ID 046d:c539)
