### ISSUE TITLE
Logitech G910v2 not working

### ISSUE THREAD

**Issue by Delido** [DarthAffe/RGB.NET#127]
Hi,

I am using JackNet RGB Sync, only my Logitech Headset and Mouse are working with.

But i cant find my connected Device "Logitech G910v2"  (http://www.devicekb.com/usb-vendor/046D/device/C335.php) 

To test the library i used this example:
https://github.com/akmadian/RGB.NET-Examples 
The same result: only mouse and Headset are working.

it seems, this SDK cant communicate with this keyboard.

Regards
Sebastian

**Comment by DarthAffe** [comment]
Hmm that's weird since the G910v2 is already included (https://github.com/DarthAffe/RGB.NET/blob/master/RGB.NET.Devices.Logitech/HID/DeviceChecker.cs#L20)
Could you test it again with the example but add ```throwExceptions: true``` as an parameter for ```surface.LoadDevices(LogitechDeviceProvider.Instance);```? I'd expect it to crash then, maybe the error message gives some insight.

**Comment by F-Lehmann** [comment]
Since i restarted my project i'm facing this problem again too. Had it working before tho. If i remeber correctly it was requiered to use the layout files from [Resources](https://github.com/DarthAffe/RGB.NET-Resources) But i forgot how to include/where to put them.

**Comment by cyberbol** [comment]
Its any way to fix that problem ?
My Logitech G910v2 also dont working. When i start JackNet RGB Sync all light on keyboard OFF.

**Comment by DarthAffe** [comment]
Hey, I don't know what the issue could be here since the 910v2 is added. Sadly I don't have access to one to verify the issue.

Could you try running this test and see if it is not working (and not showing errors).

[G910v2Test.zip](https://github.com/DarthAffe/RGB.NET/files/7508545/G910v2Test.zip)

**Comment by cyberbol** [comment]
> Hey, I don't know what the issue could be here since the 910v2 is added. Sadly I don't have access to one to verify the issue.
> 
> Could you try running this test and see if it is not working (and not showing errors).
> 
> [G910v2Test.zip](https://github.com/DarthAffe/RGB.NET/files/7508545/G910v2Test.zip)

I m not sure how run the test. If just click on G910v2Test then after i open Nothing showing and nothing happening.

**Comment by DarthAffe** [comment]
Did you completely unpack the zip?

It should open a console-window like this (it fails for me since I don't have a logitech device connected)
![image](https://user-images.githubusercontent.com/1094841/141021915-da8659a8-ad12-4c3e-b5ec-bc3f277db9cf.png)

**Comment by cyberbol** [comment]
I download Layout from discord server and it works now. Just its very long time to setup because i need to add all buttons separate to group

**Comment by cyberbol** [comment]
Its any way to copy multi from Available LED to Synchronized LED ?

**Comment by DarthAffe** [comment]
I guess the question is about JackNet RGB Sync (as there's no such thing in RGB.NET).
If that's the case I can't help - I've never used that software.

**Comment by cyberbol** [comment]
> JackNet RGB Sync
Yes, of course about JackNet RGB Sync. Im so sorry for confusing. 
I just first time using github and honestly im lost a bit. Im noob :-(

**Comment by cyberbol** [comment]
I even don't know if i can ask question here ?. I don't do anything against rules. 
If i can ask.,,then..
Do you know if it is possible to add to JackNET my GPU ?
Its PNY GeForce RTX 3080 10 GB XLR8 Gaming REVEL Edition Graphics Card. SO far i can control RGB on it only using software from PNY. Its called VelocityX.

**Comment by DarthAffe** [comment]
Like I said I can't speak for JackNet RGB Sync but for RGB.NET I can say that it isn't possible since it doesn't seem like PNY offers a way to control the lightning on the devices.
