### ISSUE TITLE
AlienwareFX Support?

### ISSUE THREAD

**Issue by slickerxcuh** [DarthAffe/RGB.NET#13]
Hi,

Last piece of my RGB puzzle, anyway to get the Alienware's AlienFX sync'd up with the bunch?

http://www.dell.com/support/home/us/en/19/product-support/product/alienware-25-gaming-monitor-aw2518h/drivers

Thank you in advance

**Comment by DarthAffe** [comment]
Hey, I'm a bit confused right now what exactly AlienFX is (I'm not able to find a download-link for the SDK and it's referred on the Roccat Talk-FX website, but there seem to be some projects around it so I'm sure it's possible to integrate it - I just need to understand what it is and how it works first.

**Comment by slickerxcuh** [comment]
I apologize for not being clear.
I have that Alienware Monitor, it has RGB behind it.  I believe you are right Roccat & Alienware https://www.roccat.org/en-US/Products/Gaming-Software/AlienFX/ are the same.  

Thank you in advance, if you could add support for these products =)

**Comment by Gurjot95** [comment]
Roccat and Alienware SDK aren't same. They both are different brands and their SDK works exclusively for their products only. TalkFX SDK for Roccat and AlienFX for Alienware only.

There is AlienFX SDK available but it's load of crap if I am being polite as the first and only version ever released was back in 2009 with so many limitations. I had to abandon its SDK and tried to reverse enginner it myself. I made my own AlienFX SDK which writes instructions directly to HID and works without any lag or limitations. Currently it only supports alienware laptops but I plan to add more devices support as I am able to reverse engineer them. You can check out here -
https://github.com/Gurjot95/AlienFX-SDK
