### ISSUE TITLE
Bypass Corsair SDK

### ISSUE THREAD

**Issue by UniCizin** [DarthAffe/RGB.NET#144]
Hello 
Not really an issue, but is there a way to bypass icue (and  the icue SDK) completely with your development?
i saw you worked with the sdk files and was wondering if you possigly found a way to use the SDK with keyboards in wireless mode.

thank you.

**Comment by Legion2** [comment]
You can try to use the corsair game sdk as it can control the profiles of iCUE directly. I created a REST API and a cli for it https://github.com/Legion2/open-cue-cli

**Comment by UniCizin** [comment]
> You can try to use the corsair game sdk as it can control the profiles of iCUE directly. I created a REST API and a cli for it https://github.com/Legion2/open-cue-cli

thank you, but this not exactly what i was looking for.
i use the 3rd Part tool Aurora (https://github.com/antonpup/Aurora) to synchronize my devices and use the chroma engine.
But the keyboard only works in usb mode because of the restrictions of the icue sdk.

icue itself gets the colors right from aurora, but does not pass it to the keyboard

**Comment by DarthAffe** [comment]
Well this is not really the scope of this project. You could check if openrgb doesn't have this restriction but in the "official" rgb.net corsair provider the corsair SDK is used.
