### ISSUE TITLE
sound blaster x ae5 support?

### ISSUE THREAD

**Issue by vadar211** [DarthAffe/RGB.NET#15]
i know they have released the sdk  for the aura lighting is it possible to have a profile that reacts to sound im asking because the rest of my rgb do just that thanks in advance

heres the link http://www.soundblaster.com/blasterx/aurorasdk/

**Comment by DarthAffe** [comment]
Hey, I wasn't aware of that SDK (thanks for the hint). I put it on the list.
It seems to be well documented but I'll need you for some testing once I get the basics implemented.

**Comment by vadar211** [comment]
yeah shore i dont mind testing it

**Comment by CryoRenegade** [comment]
I also have a Sound Blaster AE-5 if needed
