### ISSUE TITLE
Device layouts wishlist

### ISSUE THREAD

**Issue by RobertBeekman** [DarthAffe/RGB.NET#156]
With the wide range of supported devices, several limitations have come to light.
Most of these are related to changing device layouts at runtime. I think a general approach where devices and their LEDs are completely mutable would be ideal.

Just a few things I've seen pop up over time
- Removing devices after they've been registered
- Replacing the entire layout of a device
  - Maybe take a good look at how paths are resolved while you're at it. I think a configurable LayoutLoader would be nice
  - Then you can set things like the root dir, relatative layout and image dirs or even absolute dirs for everything
  - The loader could also be a good place to give feedback on why layouts weren't loaded
- Changing the shape, size and position of induvidual LEDs

**Comment by SpoinkyNL** [comment]
As a side node for people viewing this: All this is available in the [Development](https://github.com/DarthAffe/RGB.NET/tree/Development) tree.

Leaving it open for now until it's merged
