### ISSUE TITLE
Aura SDK not working with keyboard

### ISSUE THREAD

**Issue by kekkokk** [DarthAffe/RGB.NET#17]
Hi man!
I'm trying to use your wrapper to control my Asus Claymore but it throws an error:

![error](https://user-images.githubusercontent.com/15072723/38895891-8eaeaad2-4291-11e8-9c18-729b81ed4202.PNG)

This is not happening with the mainboard for example.
It seems it can't load something.

I then compiled the native sdk in a c++ project and had the same issue with the keyboard.
I was able to solve putting ClaymoreProtocol.dll (given in the test code of aura sdks) in the same folder as my exe was compiled.

I think the issue is the same but in your case (c#) I wasn't able to solve putting this file in the project folder.

Do you have any suggestion?
Thanks!

**Comment by DarthAffe** [comment]
Yeah, good old access violation ...
To be honest I've no idea if this is my fault or a bug in the SDK. I'm 100% sure that some of the issues are caused by the SDK but since I don't havce such a mainboard I wasn't able to debug with it until now.
I'll look into it.

**Comment by ericnewton76** [comment]
It'll typically be a bug/memory leak in the SDK wrapper.  A lot of the SDKs return byte arrays and without proper handling (especially in .net with GC happening) you might end up with a pointer to stuff that either got moved or early GC'd by accident.

Its funny I see that Initialize access violation error in other SDKs as well.
