### ISSUE TITLE
Unable to access the RGB.NET.Core part of the documentation.

### ISSUE THREAD

**Issue by 0x14307** [DarthAffe/RGB.NET#171]
I'm trying to look at the documentation to see how to use it however I am unable to access any documents pertaining to RGB.NET.Core.

For example: http://lib.arge.be/api/RGB.NET.Core.RGBColor.html gives a 403 error when trying to access.

Just pointing this out as an issue because for developers it is needed for some of us

EDIT: Seems like this has been extended to other sections :/

EDIT 2: Now I can't even access the website

**Comment by DarthAffe** [comment]
Hey, should work for now - but a permanent fix is still pending.

**Comment by 0x14307** [comment]
Works now, thanks!
