### ISSUE TITLE
AbstractRGBDeviceProvider leaves behind old update triggers on Dispose

### ISSUE THREAD

**Issue by SpoinkyNL** [DarthAffe/RGB.NET#193]
https://github.com/DarthAffe/RGB.NET/blob/eb3b91d8d8700c48df7663c8209f07c9301d68b6/RGB.NET.Core/Devices/AbstractRGBDeviceProvider.cs#L92-L99

After Dispose UpdateTriggers is not empty, causing old triggers to start updating again next time the device provider is added to a surface.

**Comment by DarthAffe** [comment]
For now this is considered to be not a bug.
