### ISSUE TITLE
Change corsair LedId mapping for custom devices

### ISSUE THREAD

**Issue by DarthAffe** [DarthAffe/RGB.NET#197]
As recommended in https://github.com/CorsairOfficial/cue-sdk/issues/22

**Comment by SpoinkyNL** [comment]
While we're at it, we can use this to handle motherboards and GPU too I'd imagine. Both device types are already added to the `CorsairDeviceType` enum, they just aren't handled.

Someone I can ask to test the implementation reported an issue here https://github.com/Artemis-RGB/Artemis.Plugins/issues/30
