### ISSUE TITLE
Asus AURA - No devices found

### ISSUE THREAD

**Issue by MarcinGadomski94** [DarthAffe/RGB.NET#21]
As the title specifies - while trying to hook into AURA, I am getting no devices. I have Asus Aura enabled Maximus IX Hero. It should find PCH, Back IO and 2 RGB strips.

![image](https://user-images.githubusercontent.com/23195048/41259585-6c270c2a-6dd4-11e8-9d68-1b2def5fe2c4.png)

The SDK is included in the project.

![image](https://user-images.githubusercontent.com/23195048/41259664-b11efa0e-6dd4-11e8-8bb4-05c47bcc6824.png)

**Comment by DarthAffe** [comment]
If you use the nuget-package to include RGB.NET there's no need to reference any SDK-files - but that shouldn't be the issue.
First make sure that aura is running and itself working (it needs to have lightning enabled and so on).
Then you should change the line 
```Csharp
surface.LoadDevices(new AsusDeviceProvider());
```
to
```Csharp
surface.LoadDevices(AsusDeviceProvider.Instance, throwExceptions: true);
```
I expect an exception to be thrown while loading devices.

**Comment by MarcinGadomski94** [comment]
So yeah, as you expected exception was thrown:

**System.AccessViolationException:** 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

**Comment by DarthAffe** [comment]
> Also I needed to actually include the Aura SDK into x86 folder.
Ah yeah sorry, I forgot that I changed that :p That's right, as long as you didn't install https://www.myget.org/feed/rgb_net/package/nuget/RGB.NET.Resources.Asus too

Well the AccessViolation-issue itself is well known and has two possible causes I know of:
1. Your aura is returning wrong devices (for example a second mainboard) as described there https://rog.asus.com/forum/showthread.php?97754-Access-Violation-Wrong-EnumerateMB-Result
2. I've never experienced that myself, but a lot of people could resolve that by shutting down the computer and completely cutting the power by turning of the psu and leaving off a few seconds before turning everything back on.

**Comment by MarcinGadomski94** [comment]
As I can see, the whole application needs to be running in Administrator mode to make AURA work. Same with Visual Studio if you want to debug. As long as it is running in admin mode, then everything works fine.

I believe that we can close this issue then.

**Comment by DarthAffe** [comment]
Weird, it works for me just fine without admin-mode but that might be something system specific (installation, settings, etc.)

Since it is somehow working now I'll close this, but feel free to reopen it if there are further problems.
