### ISSUE TITLE
Steelseries - setting the color on numpad 5 breaks the gamesense sdk

### ISSUE THREAD

**Issue by diogotr7** [DarthAffe/RGB.NET#240]
https://github.com/SteelSeries/gamesense-sdk/issues/85

https://github.com/SteelSeries/gamesense-sdk/issues/48

**Comment by diogotr7** [comment]
The hid workaround mentioned in one of the issues is the approach aurora uses and seems to function well.

**Comment by DarthAffe** [comment]
fixed with #241
