### ISSUE TITLE
Razer keyboard ledId are offset by one value

### ISSUE THREAD

**Issue by roxaskeyheart** [DarthAffe/RGB.NET#253]
Currently using prerelease 1.0.0-release7 and development branch.

As a test I am lighting up keys 1 through 6 on a keyboard surface. The mappings are correct for other devices, for example Corsair:

![image](https://user-images.githubusercontent.com/11515784/149271467-f129124c-bb3d-4257-8314-5252fa4e0b1e.png)

However on a Razer device, every Led seems offset by 1 Led:

![image](https://user-images.githubusercontent.com/11515784/149271522-867c6c9c-c2b0-490a-83c9-2378504fbf26.png)

I am using virtual devices for testing, but this is also the case on the physical device also. My Razer Laptop exhibits the same issue:

![image](https://user-images.githubusercontent.com/11515784/149271668-6d20973d-f939-4ee0-85ed-b24953a15576.png)

**Comment by DarthAffe** [comment]
Hey, which device (model) is reported in the error case? (if possible both virtual and physical)

**Comment by roxaskeyheart** [comment]
So it's happening on all my Razer keyboards, which includes:

- Razer Blade 15 (Physical/Laptop)
- Razer Blackwidow Chroma (Physical)
- Razer Huntsman Elite (Virtual)
