### ISSUE TITLE
MSI GP66 support

### ISSUE THREAD

**Issue by ematt** [DarthAffe/RGB.NET#256]
Hello,
Here is some info I found about the keyboard on an [MSI GP66 ](https://www.msi.com/Laptop/GP66-Leopard-11UX).
It is possible to use the steelseries SDK to control the backlight of the keyboard. On US layout the HID code for the power button is 0x66 and for FN is 0xF0 everything else works with the usual HID code.

**Comment by DarthAffe** [comment]
Hey, do you know which hid is it registererd with (for detection)?

**Comment by ematt** [comment]
Hi, Device Manager reports it as USB\VID_1038&PID_2036&REV_0000&MI_01
