### ISSUE TITLE
Device Request: BlackWidow V4

### ISSUE THREAD

**Issue by CharlieDelune** [DarthAffe/RGB.NET#305]
Razer has recently release the BlackWidow V4. Unfortunately, this device doesn't seem to be compatible with RGB.NET

**Comment by DarthAffe** [comment]
That's a detection issue, please provide the PID of the device. (You can get it by opening the properties of the device in the device manager, selecting the details tab and choose Hardware-IDs in the drop down)

![image](https://user-images.githubusercontent.com/1094841/224068820-87e2a57e-3ac2-4b3e-b4cb-59859e533c53.png)

**Comment by CharlieDelune** [comment]
![image](https://user-images.githubusercontent.com/7598363/224070019-410848c6-2b7a-4c9e-8123-26ae2cfa8b09.png)
I believe this is what you're looking for. This is listed as `HID Keyboard Device` but the manufacturer is listed as Razer Inc so I'm assuming this is right. There's multiple entries for it but they all have the same PID.

**Comment by DarthAffe** [comment]
Not 100% sure but as fas as I know 0x0306 is the "fake-device" synapse is registering.
Recent razer Keyboards where all in the 0x2... range.
