### ISSUE TITLE
Requesting support for Razer Ornata V3

### ISSUE THREAD

**Issue by Vorlanthir** [DarthAffe/RGB.NET#309]
Hello;

I'm trying to get Chromatics working with my setup, however I found it is not registering my keyboard. I'm requesting added support to the Ornata V3 thank you.

**Comment by DarthAffe** [comment]
Hey, in order to add the device I need it's PID.
Please check #305 on how to get the correct one for a razer device.

**Comment by Vorlanthir** [comment]
![image](https://user-images.githubusercontent.com/58962566/230165862-449a2be9-a2d7-4bc5-bf37-c06f0f33be76.png)

Here is an image of the Device's Hardware ID as requested.

**Comment by Vorlanthir** [comment]
(I hit close with comment on accidently, please ignore the closing and re-opening)
