### ISSUE TITLE
Does this support RGB Dram on Asus Aura boards?

### ISSUE THREAD

**Issue by Christanoid** [DarthAffe/RGB.NET#32]
Seeing how Asus's offical SDK has basically been abandoned (It didn't recieve an update in ages now) I am looking for another alternative to controll both my Asus Aura LEDs on my mainboard aswell as my G.Skill Trident Z RGB ram sticks. 
Unfortiounatley Asus never implemented the Dram control functions into their SDK so as of now there is no way for me to control it.

So as the title says I just wanna ask if your software can control the TridentZ RGB ram eventhough Asus SDK doesn't support it (yet and possibly ever) or if I will be stuck with my idea for a project here having it basically die on the step of not having an SDK to control the ram.

**Comment by DarthAffe** [comment]
I'm only using what the official SDKs are providing. If asus doesn't add support (and I agree with you that it seems unlikely right now) it won't be part of my aura-device-implementation.

**Comment by Legorobotdude** [comment]
I just downloaded the latest version of the Asus Aura sdk and in the SDK guide they do mention DRAM API. Does this mean the necessary support has been added?
[
https://www.asus.com/campaign/aura/us/SDK.html](
https://www.asus.com/campaign/aura/us/SDK.html)

**Comment by Christanoid** [comment]
Funny thing. ASUS prepared the entire documentation but the DLL is missing all the functions for Ram. So while we are told how to use it it is at the same time impossible to even use it because it doesn't exist. Last update was October 2017 so I still think it is dead.
