### ISSUE TITLE
iCUE 5 Support needed

### ISSUE THREAD

**Issue by Shiichibukai** [DarthAffe/RGB.NET#320]
Corsair decided to release iCUE 5, hopefully RGB.NET will be updated to support it soon, otherwise gotta hold off on updating iCUE.

**Comment by DarthAffe** [comment]
It should work just fine - did you experience any issues with it?

**Comment by Shiichibukai** [comment]
Nope all good, false alarm - got told iCUE 5 doesnt work and RGB.NET needs to update it hence why I didnt update to icue5 personally but turns out was a false alarm, sorry!
