### ISSUE TITLE
Update corsair-SDK

### ISSUE THREAD

**Issue by DarthAffe** [DarthAffe/RGB.NET#34]
3.0.217 is the new version.
Since there are still no changenotes a drop-in-replacement and some smoke-tests should be done.

**Comment by DarthAffe** [comment]
It seems like there's an issue with coolers - rest seem to work fine

**Comment by crashniels** [comment]
the glaive rgb also does not work. going back to 3.7.99 seems to fix the issue with the mouse and the coolers. probably an issue since 3.8.xx

**Comment by DarthAffe** [comment]
Done in https://github.com/DarthAffe/RGB.NET/commit/586d20936e4e1aa9cd0d752f46cfee05a4c72664
