### ISSUE TITLE
Num, Caps, Scroll lock leds?

### ISSUE THREAD

**Issue by Aytackydln** [DarthAffe/RGB.NET#351]
We should have Enums for these leds. Many Logitech and Razer devices have those leds controllable and they don't light up if they don't have a color set.

I want them so that they can be mapped with 3rd party integrations and they would have meaningful name with OpenRGB

**Comment by DarthAffe** [comment]
Hey, can you take a look at the pr if this works for your case?

**Comment by Aytackydln** [comment]
Yes, they are fine
