### ISSUE TITLE
Feature Request - Steelseries Apex 3

### ISSUE THREAD

**Issue by BerserkerKong02** [DarthAffe/RGB.NET#387]
Hi! Would love to see if an integration for Steelseries Apex 3 is possible!

Thanks!

**Comment by DarthAffe** [comment]
That requires the PID of the device. You can find that in the device manager in the device-properties under details -> hardware ids.

**Comment by BerserkerKong02** [comment]
Hopefully it's PID_1832

**Comment by DarthAffe** [comment]
It's added in 2.1.1-prerelease.3
I hope 10 zone is correct (at least that's what they say on the website)
