### ISSUE TITLE
Support for Gigabyte RGB Fusion and NZXT Hue

### ISSUE THREAD

**Issue by geiti94** [DarthAffe/RGB.NET#46]
wanted to know if is possible to add Gigabyte RGB fusion and NZXT hue support. 

for rgb fusion is an official sdk avaiable. that sdk can controll Gskill Trident Z RGB rams too. here is the link to the SDK: https://www.gigabyte.com/mb/rgb/sdk?fbclid=IwAR2mIF6Zrz14Aen3-dincOuh7axa_dAduEhACEf4AWRnq2GPpAxjSGPmzLM

and for the nzxt hue i found only unofficial sdks here on github like this one:

https://github.com/kusti8/hue-plus

**Comment by akmadian** [comment]
I'm working on an NZXT SDK, and I have plans to integrate it into RGB.NET, so Hue+ is coming! Unfortunately, I don't know of any Gigabyte SDK.

**Comment by ericnewton76** [comment]
nice to hear rgbfusion coming.  I was going to try my hand at it myself.

**Comment by akmadian** [comment]
@ericnewton76 As far as I know, there are no current efforts to add Gigabyte support, even though there is [an SDK](https://www.gigabyte.com/mb/rgb/sdk). If you want to try working with RGB.NET, and you have a Hue+, I would love your help with integrating my NZXT SDK with RGB.NET :)

**Comment by geiti94** [comment]
same here when rgb fusion support gets added and testing is needed i can test that too since i have a z390 aorus master board :) would be nice to get a day aura from my gpus synced with my hue+ and rgb fusion of my mainboard :)

**Comment by MelvinGr** [comment]
Would this include the NZXT Kraken devices?
