### ISSUE TITLE
C# version and getting RGB.NET working in Unity

### ISSUE THREAD

**Issue by danoli3** [DarthAffe/RGB.NET#7]
Hi,

Wondering your thoughts on getting this working with C# 3.5 or more specifically Unity Game Engine.

I've already implemented my own wrapper for Logitech and Razer's SDK's and saw your's is very similar however better structured and with more devices so hoping to pivot to using this.
I tried a while ago using it and had issues with the C# version

**Comment by DarthAffe** [comment]
Hey,

RGB.NET is using quite some things that are not supported in .NET 3.5. I'm pretty sure it would be possible to port back to that version with a bit of effort though.
To be honest, I don't see enough benefit in doing this - it seems like unity will support .NET 4.6 in the near future anyway (https://forum.unity.com/threads/upgraded-mono-net-in-editor-on-5-5-0b4.433541/).

**Comment by danoli3** [comment]
I tried to use latest 4.6 Experimental C# scripting layer for Unity and it couldn't talk to the libraries. It may have been related to the header information in the files.

I'm thinking this could be the fix:
[https://docs.microsoft.com/en-us/visualstudio/msbuild/troubleshooting-dotnet-framework-targeting-errors](https://docs.microsoft.com/en-us/visualstudio/msbuild/troubleshooting-dotnet-framework-targeting-errors?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(vs.FrameworkTargetingErrors)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.6)%26rd%3Dtrue)

**Comment by DarthAffe** [comment]
I don't really see a relation to the microsoft link. RGB.NET isn't builded against the client profile framework so there shouldn't be any problem referencing it from a never version.
Is there any error message when using it?

**Comment by DarthAffe** [comment]
Hey, with the latest beta-version of Unity RGB.NET is completely working - I just tested it with the .NETStandard build. (https://blogs.unity3d.com/2018/03/28/updated-scripting-runtime-in-unity-2018-1-what-does-the-future-hold/)

**Comment by danoli3** [comment]
Awesome!
I’d say this is fixed then
