### ISSUE TITLE
Possible new AURA SDK

### ISSUE THREAD

**Issue by rag3rac3r** [DarthAffe/RGB.NET#71]
Not really an issue, but while poking around on the ASUS website i managed to come across what appears to be version 3.0 off the AURA SDK, where some files are dated august/october last year, and some are dated in march this year.

It is stated to have been re-structured from the ground up, i know it has been a few issues with ASUS product and that the SDK have not been updated - could this possible be an update and something not already in RGB.Net?

URL to it:
https://www.asus.com/campaign/aura/uk/AURA-ready.php

**Comment by DarthAffe** [comment]
I'm currently working on this and first test showed that it works. The only open issue right now is, that the new SDK seems to doesn't support reading colors from the LEDs, which would be a huge regression for most users right now.
I'm not sure how to deal with this until now :(

**Comment by akmadian** [comment]
@DarthAffe Maybe it's possible to transplant the syncback capabilities from the original SDK into RGB.NET? If not, maybe it's possible to find a way to make the two versions work in tandem, using the old one for getting leds, and the new one for device discovery and setting leds?

**Comment by DarthAffe** [comment]
since the old one isn't working properly with the newest version of aura (which is required to use the new sdk) i don't think this will be an option.

**Comment by kekkokk** [comment]
Hi @DarthAffe, thanks for the awesome work.
I found that there's a pull request in Aurora software with piece of your code, and I'm trying to help finding out why my Asus Claymore does not work.

More precisely I'm trying to understand where did you find the **documentation** to use the V3 SDKs, and where did you find Interop.AuraServiceLib.dll

Can you briefly explain your integration process? From where did you start?

I would very appreciate if you spend 1 minute to clarify me these things.
I'm an absolute newbie in Windows + c#. 

Thanks!
Francesco.

**Comment by DarthAffe** [comment]
https://www.asus.com/campaign/aura/uk/AURA-ready.php

**Comment by F-Lehmann** [comment]
Hi,
I know the Issue closed, but on my end it seems like Asus again has replaced the SDK on their website with the old one and the new one could not be found anymore. Unfortunatly i dont have any copy of if anymore? Does someone have a mirror to it?

**Comment by DarthAffe** [comment]
Hmm seems like they reworked the rog site and completely removed the sdk. This is the sdk-version I worked with but it might not be the latest that was available.
[http://arge.be/archive/ROG AURA SDK_release.zip](http://arge.be/archive/ROG AURA SDK_release.zip)

**Comment by F-Lehmann** [comment]
I once again have to thank you very much
