### ISSUE TITLE
Does the RGB Sync work with ASRock?

### ISSUE THREAD

**Issue by NithinD1** [DarthAffe/RGB.NET#94]
Hey @DarthAffe , 

So I am trying to sync my Asus GPU, my Corsair ram (which syncs with my Asus GPU with aura sync), and my ASRock motherboard lighting, RGB Case fans, and my light strips (and these 3 are controlled with ASRock Polychrome). So someone suggested this to me on Reddit and I am not sure if this works with ASRock because I need to sync ASRock Polychrome and Asus aura sync. I am new to all this RGB stuff cause I am a first time builder so I am literally pulling the hair out of my head figuring out a way to sync all the RGB.

Thanks! 

Here is my PC build:
PCPartPicker Part List: https://pcpartpicker.com/list/kQYshg

CPU: Intel Core i5-8600K 3.6 GHz 6-Core Processor  ($244.99 @ B&H) 
CPU Cooler: Corsair H115i PRO 55.4 CFM Liquid CPU Cooler  ($139.99 @ Amazon) 
Motherboard: ASRock Z390 Phantom Gaming 9 ATX LGA1151 Motherboard  ($249.99 @ Amazon) 
Memory: Corsair Vengeance RGB Pro 16 GB (2 x 8 GB) DDR4-3000 Memory  ($79.98 @ Amazon) 
Storage: Samsung 960 EVO 250 GB M.2-2280 NVME Solid State Drive  ($119.89 @ Amazon) 
Storage: Western Digital Caviar Blue 1 TB 3.5" 7200RPM Internal Hard Drive  ($39.99 @ Newegg) 
Video Card: Asus GeForce GTX 1070 Ti 8 GB ROG STRIX Video Card  (Purchased For $300.00) 
Case: Corsair SPEC-DELTA RGB ATX Mid Tower Case  ($79.99 @ Best Buy) 
Power Supply: EVGA SuperNOVA G2 750 W 80+ Gold Certified Fully Modular ATX Power Supply  ($179.98 @ Amazon) 
Custom: RGB LED Light Strip - Speclux LED Strip for Modding PC Case, M/B with 4pin RGB Header Compatible with Asus Aura, Asrock RGB Led, Gigabyte RGB Fusion, MSI Mystic Light, 3 PCS SMD 5050 PC LED Strip  ($16.98 @ Amazon) 
Total: $1451.78
Prices include shipping, taxes, and discounts when available
Generated by PCPartPicker 2019-12-09 20:29 EST-0500

**Comment by SpoinkyNL** [comment]
Hi, unfortunately ASRock Polysync does not provide an SDK. They do however integrate with Razer Synapse, which is supported: https://stackoverflow.com/a/57846872/5015269.

I'm not sure how that works, but if you can control your ASRock stuff from Razer Synapse, the Razer Synapse SDK should be able to control it as well, allowing you to use RGB Sync with it.

**Comment by NithinD1** [comment]
Yea but I don’t own razer products therefore I can’t use there software. Thanks for the help!

**Comment by NithinD1** [comment]
@SpoinkyNL 

I found this on how to find the SDK: http://forum.asrock.com/forum_posts.asp?TID=8350&title=rgb-api-sdk-for-custom-software

Also found out that I can use razer synapse without razer products so thanks for that will try it out.

**Comment by SpoinkyNL** [comment]
I saw that topic too when doing some searching but it doesn't actually provide a SDK, just some links to firmware, which unless we reverse engineer it won't help us
